bollywood/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bollywood.views.home', name='home'),
    # url(r'^bollywood/', include('bollywood.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', TemplateView.as_view(template_name='home.html')),
    #url(r'^$', TemplateView.as_view(template_name='index.html')),
	#adding new view as homepage to display shows
	url(r'^$', 'shows.views.home_page'),
    url(r'^show/$', 'shows.views.show_list'),
    url(r'^show/(?P<show_slug>[-\w]+)/$', 'shows.views.show_detail'),
    url(r'^show/(?P<show_slug>[-\w]+)/(?P<episode_id>[-\w]+)$', 'shows.views.episode_detail'),
    url(r'^movie/$', 'shows.views.movie_list'),
    url(r'^movie/(?P<movie_slug>[-\w]+)/$', 'shows.views.movie_detail'),
    url(r'^accounts/', include('userena.urls')),  
    url(r'^playlist/(?P<show_slug>[-\w]+)/(?P<episode_id>[-\w]+)$', 'shows.views.show_playlist'),
    url(r'^mtv/(?P<mtv_id>[-\w]+)/$', 'shows.views.mtv'),
)

shows/models.py
# encoding: utf-8
from django.db import models
from django.utils.translation import ugettext as _

# http://xml.coverpages.org/country3166.html
COUNTRIES = (
	('AD', _('Andorra')),
	('AE', _('United Arab Emirates')),
	('AF', _('Afghanistan')),
	('AG', _('Antigua & Barbuda')),
	('AI', _('Anguilla')),
	('AL', _('Albania')),
	('AM', _('Armenia')),
	('AN', _('Netherlands Antilles')),
	('AO', _('Angola')),
	('AQ', _('Antarctica')),
	('AR', _('Argentina')),
	('AS', _('American Samoa')),
	('AT', _('Austria')),
	('AU', _('Australia')),
	('AW', _('Aruba')),
	('AZ', _('Azerbaijan')),
	('BA', _('Bosnia and Herzegovina')),
	('BB', _('Barbados')),
	('BD', _('Bangladesh')),
	('BE', _('Belgium')),
	('BF', _('Burkina Faso')),
	('BG', _('Bulgaria')),
	('BH', _('Bahrain')),
	('BI', _('Burundi')),
	('BJ', _('Benin')),
	('BM', _('Bermuda')),
	('BN', _('Brunei Darussalam')),
	('BO', _('Bolivia')),
	('BR', _('Brazil')),
	('BS', _('Bahama')),
	('BT', _('Bhutan')),
	('BV', _('Bouvet Island')),
	('BW', _('Botswana')),
	('BY', _('Belarus')),
	('BZ', _('Belize')),
	('CA', _('Canada')),
	('CC', _('Cocos (Keeling) Islands')),
	('CF', _('Central African Republic')),
	('CG', _('Congo')),
	('CH', _('Switzerland')),
	('CI', _('Ivory Coast')),
	('CK', _('Cook Iislands')),
	('CL', _('Chile')),
	('CM', _('Cameroon')),
	('CN', _('China')),
	('CO', _('Colombia')),
	('CR', _('Costa Rica')),
	('CU', _('Cuba')),
	('CV', _('Cape Verde')),
	('CX', _('Christmas Island')),
	('CY', _('Cyprus')),
	('CZ', _('Czech Republic')),
	('DE', _('Germany')),
	('DJ', _('Djibouti')),
	('DK', _('Denmark')),
	('DM', _('Dominica')),
	('DO', _('Dominican Republic')),
	('DZ', _('Algeria')),
	('EC', _('Ecuador')),
	('EE', _('Estonia')),
	('EG', _('Egypt')),
	('EH', _('Western Sahara')),
	('ER', _('Eritrea')),
	('ES', _('Spain')),
	('ET', _('Ethiopia')),
	('FI', _('Finland')),
	('FJ', _('Fiji')),
	('FK', _('Falkland Islands (Malvinas)')),
	('FM', _('Micronesia')),
	('FO', _('Faroe Islands')),
	('FR', _('France')),
	('FX', _('France, Metropolitan')),
	('GA', _('Gabon')),
	('GB', _('United Kingdom (Great Britain)')),
	('GD', _('Grenada')),
	('GE', _('Georgia')),
	('GF', _('French Guiana')),
	('GH', _('Ghana')),
	('GI', _('Gibraltar')),
	('GL', _('Greenland')),
	('GM', _('Gambia')),
	('GN', _('Guinea')),
	('GP', _('Guadeloupe')),
	('GQ', _('Equatorial Guinea')),
	('GR', _('Greece')),
	('GS', _('South Georgia and the South Sandwich Islands')),
	('GT', _('Guatemala')),
	('GU', _('Guam')),
	('GW', _('Guinea-Bissau')),
	('GY', _('Guyana')),
	('HK', _('Hong Kong')),
	('HM', _('Heard & McDonald Islands')),
	('HN', _('Honduras')),
	('HR', _('Croatia')),
	('HT', _('Haiti')),
	('HU', _('Hungary')),
	('IN', _('India')),
	('ID', _('Indonesia')),
	('IE', _('Ireland')),
	('IL', _('Israel')),
	('IO', _('British Indian Ocean Territory')),
	('IQ', _('Iraq')),
	('IR', _('Islamic Republic of Iran')),
	('IS', _('Iceland')),
	('IT', _('Italy')),
	('JM', _('Jamaica')),
	('JO', _('Jordan')),
	('JP', _('Japan')),
	('KE', _('Kenya')),
	('KG', _('Kyrgyzstan')),
	('KH', _('Cambodia')),
	('KI', _('Kiribati')),
	('KM', _('Comoros')),
	('KN', _('St. Kitts and Nevis')),
	('KP', _('Korea, Democratic People\'s Republic of')),
	('KR', _('Korea, Republic of')),
	('KW', _('Kuwait')),
	('KY', _('Cayman Islands')),
	('KZ', _('Kazakhstan')),
	('LA', _('Lao People\'s Democratic Republic')),
	('LB', _('Lebanon')),
	('LC', _('Saint Lucia')),
	('LI', _('Liechtenstein')),
	('LK', _('Sri Lanka')),
	('LR', _('Liberia')),
	('LS', _('Lesotho')),
	('LT', _('Lithuania')),
	('LU', _('Luxembourg')),
	('LV', _('Latvia')),
	('LY', _('Libyan Arab Jamahiriya')),
	('MA', _('Morocco')),
	('MC', _('Monaco')),
	('MD', _('Moldova, Republic of')),
	('MG', _('Madagascar')),
	('MH', _('Marshall Islands')),
	('ML', _('Mali')),
	('MN', _('Mongolia')),
	('MM', _('Myanmar')),
	('MO', _('Macau')),
	('MP', _('Northern Mariana Islands')),
	('MQ', _('Martinique')),
	('MR', _('Mauritania')),
	('MS', _('Monserrat')),
	('MT', _('Malta')),
	('MU', _('Mauritius')),
	('MV', _('Maldives')),
	('MW', _('Malawi')),
	('MX', _('Mexico')),
	('MY', _('Malaysia')),
	('MZ', _('Mozambique')),
	('NA', _('Namibia')),
	('NC', _('New Caledonia')),
	('NE', _('Niger')),
	('NF', _('Norfolk Island')),
	('NG', _('Nigeria')),
	('NI', _('Nicaragua')),
	('NL', _('Netherlands')),
	('NO', _('Norway')),
	('NP', _('Nepal')),
	('NR', _('Nauru')),
	('NU', _('Niue')),
	('NZ', _('New Zealand')),
	('OM', _('Oman')),
	('PA', _('Panama')),
	('PE', _('Peru')),
	('PF', _('French Polynesia')),
	('PG', _('Papua New Guinea')),
	('PH', _('Philippines')),
	('PK', _('Pakistan')),
	('PL', _('Poland')),
	('PM', _('St. Pierre & Miquelon')),
	('PN', _('Pitcairn')),
	('PR', _('Puerto Rico')),
	('PT', _('Portugal')),
	('PW', _('Palau')),
	('PY', _('Paraguay')),
	('QA', _('Qatar')),
	('RE', _('Reunion')),
	('RO', _('Romania')),
	('RU', _('Russian Federation')),
	('RW', _('Rwanda')),
	('SA', _('Saudi Arabia')),
	('SB', _('Solomon Islands')),
	('SC', _('Seychelles')),
	('SD', _('Sudan')),
	('SE', _('Sweden')),
	('SG', _('Singapore')),
	('SH', _('St. Helena')),
	('SI', _('Slovenia')),
	('SJ', _('Svalbard & Jan Mayen Islands')),
	('SK', _('Slovakia')),
	('SL', _('Sierra Leone')),
	('SM', _('San Marino')),
	('SN', _('Senegal')),
	('SO', _('Somalia')),
	('SR', _('Suriname')),
	('ST', _('Sao Tome & Principe')),
	('SV', _('El Salvador')),
	('SY', _('Syrian Arab Republic')),
	('SZ', _('Swaziland')),
	('TC', _('Turks & Caicos Islands')),
	('TD', _('Chad')),
	('TF', _('French Southern Territories')),
	('TG', _('Togo')),
	('TH', _('Thailand')),
	('TJ', _('Tajikistan')),
	('TK', _('Tokelau')),
	('TM', _('Turkmenistan')),
	('TN', _('Tunisia')),
	('TO', _('Tonga')),
	('TP', _('East Timor')),
	('TR', _('Turkey')),
	('TT', _('Trinidad & Tobago')),
	('TV', _('Tuvalu')),
	('TW', _('Taiwan, Province of China')),
	('TZ', _('Tanzania, United Republic of')),
	('UA', _('Ukraine')),
	('UG', _('Uganda')),
	('UM', _('United States Minor Outlying Islands')),
	('US', _('United States of America')),
	('UY', _('Uruguay')),
	('UZ', _('Uzbekistan')),
	('VA', _('Vatican City State (Holy See)')),
	('VC', _('St. Vincent & the Grenadines')),
	('VE', _('Venezuela')),
	('VG', _('British Virgin Islands')),
	('VI', _('United States Virgin Islands')),
	('VN', _('Viet Nam')),
	('VU', _('Vanuatu')),
	('WF', _('Wallis & Futuna Islands')),
	('WS', _('Samoa')),
	('YE', _('Yemen')),
	('YT', _('Mayotte')),
	('YU', _('Yugoslavia')),
	('ZA', _('South Africa')),
	('ZM', _('Zambia')),
	('ZR', _('Zaire')),
	('ZW', _('Zimbabwe')),
	('ZZ', _('Unknown or unspecified country')),
)


class Actor(models.Model):
	actor_name = models.CharField(max_length=200)
	actor_slug_name = models.SlugField(unique=True,
										help_text=u'This is a permalink for Actor. Ensure name is unique.')
	

	def __unicode__(self):
		return self.actor_name


class Director(models.Model):
	director_name = models.CharField(max_length=200)
	director_slug_name = models.SlugField(unique=True,
										help_text=u'This is a permalink for Director. Ensure name is unique.')
	
	def __unicode__(self):
		return self.director_name


class Genre(models.Model):
	genre_type = models.CharField(max_length=200)
	genre_slug_type = models.SlugField(unique=True,
										help_text=u'This is a permalink for Genre. Ensure name is unique.')
	
	def __unicode__(self):
		return self.genre_type

class Network(models.Model):
	network_name = models.CharField(max_length=100)
	network_slug_name = models.SlugField(unique=True,
										help_text=u'This is a permalink for Network. Ensure name is unique.')
	
	def __unicode__(self):
		return self.network_name


class Production_House(models.Model):
	production_house_name = models.CharField(max_length=100)
	production_house_slug_name = models.SlugField(unique=True,
										help_text=u'This is a permalink for Production House. Ensure name is unique.')
	
	class Meta:
	    verbose_name = u'Production House'
	    verbose_name_plural = u'Production Houses'

	def __unicode__(self):
		return self.production_house_name


class Episode(models.Model):
	episode_number = models.IntegerField()
	episode_name = models.CharField(max_length=200)
	episode_slug_name = models.SlugField(unique=True,
										help_text=u'This is a permalink for Episode. Ensure name is unique.')
	episode_duration = models.IntegerField(blank=True, null=True, 
											help_text=u'Duration of episode in minutes')
	episode_trailer = models.CharField(max_length=11, 
									blank=True, 
									help_text=u'Key in the 11 characters Youtube ID. Eg M0jmSsQ5ptw',
									verbose_name='Episode link')
	episode_startdate = models.DateField(blank=True, null=True)
	
	###Mayank: added the MTV link to support MTV video embedding which is differenct from Youtube
	episode_mtv_link=models.TextField(max_length=6000,
									blank=True,
									help_text=u'Copy and paste the embed video option from MTV website')

	def __unicode__(self):
		return self.episode_name


class Show(models.Model):
	show_name = models.CharField(max_length=200)
	show_slug_name = models.SlugField(unique=True,
										help_text=u'This is a permalink for Show. Ensure name is unique.')
	show_abbrev = models.CharField(max_length=10,
										help_text=u'Choose a unique abbreviation. Max length 10 characters.')
	show_pix1 = models.CharField(max_length=200,
									blank=True, null=True, 
									help_text=u'Insert picture URL here. Max length 200 characters. If longer use bit.ly to shorten')
	show_pix2 = models.CharField(max_length=200,
									blank=True, null=True, 
									help_text=u'Insert picture URL here. Max length 200 characters. If longer use bit.ly to shorten')
	show_pix3 = models.CharField(max_length=200,
									blank=True, null=True, 
									help_text=u'Insert picture URL here. Max length 200 characters. If longer use bit.ly to shorten')
	show_startdate = models.DateField(blank=True, null=True)
	show_current_episode = models.IntegerField(blank=True, null=True)
	show_official_site = models.URLField(blank=True)

shows/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from .models import Show, Episode, Movie, Genre, MTV

from django.http import Http404

def home_page(request):
	shows = Show.objects.all()
	movies = Movie.objects.all()
	genres = Genre.objects.all()
	return render_to_response('homepage.html',
            				{'shows': shows, 'movies': movies, 'genres': genres},
                            context_instance=RequestContext(request))



def show_list(request):
	shows = Show.objects.all()
	
	return render_to_response('showlist.html',
            				{'shows': shows},
                            context_instance=RequestContext(request))

def show_detail(request, show_slug):
    try:
        show = Show.objects.get(show_slug_name=show_slug)
    except Show.DoesNotExist:
        raise Http404
    return render_to_response('showdetail.html',
            				{'show': show},
                            context_instance=RequestContext(request))


def show_playlist(request, show_slug, episode_id):
    try:
        show = Show.objects.get(show_slug_name=show_slug)
        episode = Episode.objects.get(id = episode_id)
    except Show.DoesNotExist:
        raise Http404
    return render_to_response('showplaylist.html',
                            {'show': show, 'episode': episode},
                            context_instance=RequestContext(request))


def episode_detail(request, show_slug, episode_id):
    try:
        episode = Episode.objects.get(id = episode_id)
    except Show.DoesNotExist:
        raise Http404
    return render_to_response('episodedetail.html',
            				{'episode': episode},
                            context_instance=RequestContext(request))


def movie_list(request):
    movies = Movie.objects.all()
    
    return render_to_response('movielist.html',
                            {'movies': movies},
                            context_instance=RequestContext(request))

def movie_detail(request, movie_slug):
    try:
        movie = Movie.objects.get(movie_slug_name=movie_slug)
    except Movie.DoesNotExist:
        raise Http404
    return render_to_response('moviedetail.html',
                            {'movie': movie},
                            context_instance=RequestContext(request))


def mtv(request, mtv_id):
    try:
        mtv = MTV.objects.get(id = mtv_id)
    except MTV.DoesNotExist:
        raise Http404
    return render_to_response('mtv.html',
                            {'mtv': mtv},
                            context_instance=RequestContext(request))

shows/templates/episodedetail.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ episode.episode_name }}{% endblock %}

{% block content %}
<h2>{{ episode.episode_name }}</h2>

<br>

<h5>Episode Number:</h5>
{{ episode.episode_number }}<br>

{% if episode.episode_duration %}
<h5>Duration:</h5>
{{ episode.episode_duration }}<br>
{% endif %}

{% if episode.episode_trailer %}
<h5>Trailer:</h5>
<iframe width="560" height="315" src="http://www.youtube.com/embed/{{ episode.episode_trailer }}?rel=0&iv_load_policy=3" frameborder="0" allowfullscreen></iframe><br>
{% endif %}

{% if episode.episode_startdate %}
<h5>Start Date:</h5>
{{ episode.episode_startdate }}<br>
{% endif %}


{% endblock %}

shows/templates/homepage.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - List of Shows{% endblock %}

{% block content %}


    <div class="container">
      <!--  Carousel -->
      <!--  consult Bootstrap docs at 
            http://twitter.github.com/bootstrap/javascript.html#carousel -->

      <div class="span10 offset1 pagination-centered">
      	<br>
      	<h1>Start watching these shows for free</h1>
      	<br>
      <div id="this-carousel-id" class="carousel slide">
      	
        <div class="carousel-inner">
          

          <div class="item active">
            <a href="/show/koffee-karan/">  
            	<img src="https://s3.amazonaws.com/Dekkho-Images/TV+Shows/Koffee+With+Karan+header.jpg" width="975" height="427" alt="Koffee with Karan" />
            

            <div class="carousel-caption">
              <p>Koffee with Karan</p>
            </div>

            <!--
			<div class="container">
					<div class="carousel-caption">
					  <a class="btn btn-large btn-primary" href="/show/koffee-karan/">Watch Now</a>
					</div>
			</div>
			-->
			</a>
          </div>

          <!--
          <div class="item">
            <a href="">
              <img src="{{ STATIC_URL }}img/kbc.jpg" width="975" height="427" alt="Kaun Banega Crorepati" />
            </a>

           
            <div class="carousel-caption">
              <p>Kaun Banega Crorepati </p>
            </div>
        	
          </div>
      		-->

      	<!--
          <div class="item">
            <a href="/show/superdude/">
              <img src="{{ STATIC_URL }}img/superdude.jpg" width="975" height="427" alt="Super Dude" />
          
            
            
            <div class="carousel-caption">
              <p>Super Dude</p>
             
            </div>
        	</a>
          </div>
		-->

          <div class="item">
            <a href="/show/dance-india-dance/">
              <img src="{{ STATIC_URL }}img/DanceIndiaDance.jpg" width="975" height="427" alt="DanceIndiaDance" />
           
      
            <div class="carousel-caption">
              <p>Dance India Dance</p>
             
            </div>
       
       		</a>
          </div>
        </div><!-- .carousel-inner -->
        <!--  next and previous controls here
              href values must reference the id for this carousel -->
          <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
          <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
      </div><!-- .carousel -->
      <!-- end carousel -->
  	  </div>
	  

	  
	  <div class="row">


							<div class="tabbable span12">
								<ul class="nav nav-pills">
									<li class="active"><a href="#tabs1-pane5" data-toggle="tab">All Shows</a></li>
									<li><a href="#tabs1-pane6" data-toggle="tab">All Movies</a></li>
									<li><a href="#tabs1-pane1" data-toggle="tab">Family</a></li>
									<li><a href="#tabs1-pane2" data-toggle="tab">Talk Shows</a></li>
									<li><a href="#tabs1-pane3" data-toggle="tab">Music</a></li>
									
									<!-- <li><a href="#tabs1-pane4" data-toggle="tab">Reality Show</a></li> -->
									
									
								</ul>
								<div class="tab-content">
									<div class="tab-pane" id="tabs1-pane1">
										<div clas="row">
												<ul class="media-grid">
													{% if genres %}
															{% for genre in genres %}
																{%if genre.show_set.all|length and genre.genre_type = 'Family' %}
																	<p>	<span class="label label-info">{{genre.genre_type}} </span> </p>
																	
																		{% for show in genre.show_set.all %}
																			{%if show.show_pix1 %}
																				<div class="span16"> 
																					<br>
																					<a href="/show/{{ show.show_slug_name }}"> <img src = "{{ show.show_pix1 }}" width = "200px"> 
																					<br>
																					<div class = "pagination-centered">
																						{{ show.show_name }}
																					</div>
																					</a>

																				</div>
																			{% endif %}
																		{% endfor %}
																{%endif%}
															{% endfor %}
														
													{% else %}
														<p>No genre available.</p>
													{% endif %}
													</ul>
											</div>
										</div>
									<div class="tab-pane" id="tabs1-pane2">
										<div clas="row">
												<ul class="media-grid">
													{% if genres %}
															{% for genre in genres %}
																{%if genre.show_set.all|length and genre.genre_type = 'Talk Show' %}
																	<p>	<span class="label label-info">{{genre.genre_type}} </span> </p>
																		{% for show in genre.show_set.all %}
																			{%if show.show_pix1 %}
																				<div class="span16"> 
																					<br>
																					<a href="/show/{{ show.show_slug_name }}"> <img src = "{{ show.show_pix1 }}" width = "200px"> 
																					<br>
																					<div class = "pagination-centered">
																						{{ show.show_name }}
																					</div>
																					</a>
																				</div>
																			{% endif %}
																		{% endfor %}
																{%endif%}
															{% endfor %}
														
													{% else %}
														<p>No genre available.</p>
													{% endif %}
													</ul>
											</div>
										
									</div>
									<div class="tab-pane" id="tabs1-pane3">
										<div clas="row">
												<ul class="media-grid">
													{% if genres %}
															{% for genre in genres %}
																{%if genre.show_set.all|length and genre.genre_type = 'Music themed' %}
																<p><span class="label label-info">{{genre.genre_type}} </span> </p>
																		{% for show in genre.show_set.all %}
																			{%if show.show_pix1 %}
																				<div class = "span16"> 
																					<br>
																					<a href="/show/{{ show.show_slug_name }}"> <img src = "{{ show.show_pix1 }}" width = "200px">
																					<br>
																					<div class = "pagination-centered">
																						{{ show.show_name }}
																					</div>
																					</a>
																				</div>
																			{% endif %}
																		{% endfor %}
																{%endif%}
															{% endfor %}
														
													{% else %}
														<p>No genre available.</p>
													{% endif %}
													</ul>
											</div>
									</div>
									
									<div class="tab-pane" id="tabs1-pane4">
										<div>
												<ul class="media-grid">
													{% if genres %}
															{% for genre in genres %}
																{%if genre.show_set.all|length and genre.genre_type = 'Reality Shows' %}
																<p>	<span class="label label-info">{{genre.genre_type}} </span> </p>
																		{% for show in genre.show_set.all %}
																			{%if show.show_pix1 %}
																				<div class ="span16"> 
																					<br>
																					<a href="/show/{{ show.show_slug_name }}"> <img src = "{{ show.show_pix1 }}" width = "200px">
																					<br>
																					<div class = "pagination-centered">
																						{{ show.show_name }}
																					</div>
																					</a>
																				</div>
																			{% endif %}
																		{% endfor %}
																{%endif%}
															{% endfor %}
														
													{% else %}
														<p>No genre available.</p>
													{% endif %}
													</ul>
											</div>
									</div>

									
									
									
									
																		
																		
																		<!--Thumnails starts here-->
									<div class="tab-pane active" id="tabs1-pane5">
										<div class ="row">
												<ul class="media-grid">
												{% if shows %}
													<ul>
														<p><span class="label label-info">All Shows</span> </p>
														{% for show in shows %}
															{%if show.show_pix1 %}


																<div class = "span16"> 
																	<br>
																	<a href="/show/{{ show.show_slug_name }}"> <img src = "{{ show.show_pix1 }}" width = "200px">
																		<br>
																		<div class = "pagination-centered">
																						{{ show.show_name }}
																		</div>
																		</a>
																</div>
															{%else%}
														
															{% endif %}
														{% endfor %}
													</ul>
												{% else %}
													<p>No shows available.</p>
												{% endif %}
											</ul>
										</div>
										</div>
									<!--Thumnails ends here-->
							

	  
	  
	  

									<!--movies thumbnails starts here	-->
	  								<div class="tab-pane" id="tabs1-pane6">
										<div class ="row">
												<ul class="media-grid">
												{% if movies %}
											<!-- <p>Found {{ movies|length }} movie{{ movies|pluralize }}.</p> -->
												<ul>
													<p><span class="label label-info">All Movies</span> </p>
													{% for movie in movies %}
														<a href="/movie/{{ movie.movie_slug_name }}"> 
														{%if movie.movie_pix1 %}
															<div class = "span16"> 
																<br>
																<a href="/movie/{{ movie.movie_slug_name }}"> <img src = "{{ movie.movie_pix1 }}" width = "200px">
																	<br>
																					<div class = "pagination-centered">
																						{{ movie.movie_name }}
																					</div>
																					</a>
															</div>
														{%else%}
													
														{% endif %}
													{% endfor %}
												</ul>
											{% else %}
												<p>No movies available.</p>
											{% endif %}
											</ul>

										</div>
										</div>
									<!--movies thumbnails ends here-->
									
							
	  



							</div><!-- /.tab-content -->
						</div><!-- /.tabbable -->
			</div><!-- /.row -->
	  
	  
	  
	  


{% endblock %}

shows/templates/movielist.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - List of Movies{% endblock %}

{% block content %}

{% if movies %}
    <p>Found {{ movies|length }} movie{{ movies|pluralize }}.</p>
    <ul>
        {% for movie in movies %}
        <li><a href="/movie/{{ movie.movie_slug_name }}">{{ movie.movie_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No movies available.</p>
{% endif %}

{% endblock %}

shows/templates/mtv.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ mtv.mtv_name }}{% endblock %}

{% block content %}
<h2>{{ mtv.mtv_name }}</h2>

<br>

<h5>Embed Code:</h5>

{{ mtv.mtv_embed_code|safe }}<br>


{% endblock %}

shows/templates/showlist.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - List of Shows{% endblock %}

{% block content %}

{% if shows %}
    <p>Found {{ shows|length }} show{{ shows|pluralize }}.</p>
    <ul>
        {% for show in shows %}
        <li><a href="/show/{{ show.show_slug_name }}">{{ show.show_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No shows available.</p>
{% endif %}

{% endblock %}